name: Build and Push Docker image to GCR

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  workflow_dispatch: {}

permissions:
  contents: read

env:
  # Mandatory settings (fail-fast if not provided)
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  # Defaults
  GCR_HOST: gcr.io
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Validate required variables
        run: |
          set -euo pipefail
          if [ -z "${GCP_PROJECT_ID:-}" ]; then
            echo "GCP_PROJECT_ID (Repository Variable) is required" >&2
            exit 1
          fi
          if [ -z "${{ secrets.GCP_SA_KEY }}" ]; then
            echo "GCP_SA_KEY (Repository Secret) is required" >&2
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GCR_HOST }}/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GCR_HOST }}
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
